export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "secondary": "#ffb4ab",
        "surface-dim": "#131313",
        "tertiary-container": "#e5b700",
        "on-primary-fixed": "#001f29",
        "surface-variant": "#353534",
        "on-background": "#e5e2e1",
        "surface-bright": "#393939",
        "on-secondary": "#690006",
        "on-secondary-container": "#ffe2de",
        "surface": "#131313",
        "on-primary-container": "#005369",
        "primary": "#9de2ff",
        "error-container": "#93000a",
        "outline": "#869399",
        "primary-container": "#00ccff",
        "inverse-primary": "#006782",
        "primary-fixed-dim": "#5ed4ff",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed": "#410002",
        "tertiary-fixed-dim": "#f1c100",
        "surface-container-highest": "#353534",
        "surface-tint": "#5ed4ff",
        "primary-fixed": "#bbe9ff",
        "on-tertiary-fixed-variant": "#584400",
        "secondary-fixed": "#ffdad6",
        "on-secondary-fixed-variant": "#93000c",
        "outline-variant": "#3c494e",
        "on-tertiary-fixed": "#241a00",
        "secondary-container": "#d30017",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#ffe08b",
        "on-tertiary": "#3d2f00",
        "background": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "tertiary": "#ffd44f",
        "on-tertiary-container": "#5e4900",
        "on-primary-fixed-variant": "#004d63",
        "surface-container-low": "#1c1b1b",
        "on-surface": "#e5e2e1",
        "on-primary": "#003545",
        "secondary-fixed-dim": "#ffb4ab",
        "inverse-surface": "#e5e2e1",
        "on-surface-variant": "#bbc8d0",
        "inverse-on-surface": "#313030"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "lg": "16px",
        "xs": "4px",
        "unit": "4px",
        "xl": "24px",
        "sm": "8px",
        "gutter": "1px",
        "md": "12px"
      },
      fontFamily: {
        "label-bold": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
        "mono-data": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "label-bold": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-lg": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "mono-data": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "500" }],
        "body-md": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
